### ISSUE TITLE
New style sheets uglify supporters table

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-chapter-bristol-uk#16]
**Describe what change you would like** :  
OWASP has recently introduced new styling for the chapter (and project) pages
This has made the table for our supporters logos look ugly, and another way of arranging the supporters logos should be found

**Context** :  
<img width="955" alt="Screenshot 2023-07-16 at 21 16 22" src="https://github.com/OWASP/www-chapter-bristol-uk/assets/29352392/bf405632-77c8-48ca-bfdf-dc74c2128ae6">

**Comment by craigfrancis** [comment]
Be careful for what you wish for... I've replaced it with a list (as technically it is a list, not a table), and I've removed some of the transparent space on the ImmersiveLabs and ForgeRockLogo logos (although I suspect I need to wait for the cache to forget about the old images)... but, erm, I'm not sure it looks better.

**Comment by jgadsden** [comment]
good point @craigfrancis , using a list looks a bit confusing and a bit jumbled
probably a table is better, but the style that OWASP has recently introduced is striped tables which makes the first row of logos look really strange

**Comment by craigfrancis** [comment]
Huh, it looks like inline styles are allowed:

https://owasp.org/www-chapter-bristol-uk/

How strange, I'd have thought OWASP would have blocked that (says he now wondering what inline JavaScript would be allowed, considering we are on the top "owasp.org" domain, and setting cookies...)

**Comment by jgadsden** [comment]
I bow to you @craigfrancis , and can now close this issue - many thanks
