### ISSUE TITLE
Add web site URL

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-chapter-bristol-uk#5]
There is a field in the repo title area for a website, it would be good to have this filled in with https://owasp.org/www-chapter-bristol-uk/ . Also this could appear in a github README.md file in this repo?

**Comment by jgadsden** [comment]
I have provided an example of this at : https://github.com/jgadsden/www-chapter-bristol-uk

**Comment by craigfrancis** [comment]
Has that fixed it?

**Comment by jgadsden** [comment]
Yes, that is perfect - thankyou

**Comment by jgadsden** [comment]
hmmm ... couldn't have a README.md file as well could we? :-)

**Comment by craigfrancis** [comment]
Got one in mind?

**Comment by craigfrancis** [comment]
Quick look at the others, only 1 has a README file, shall we steal/copy it?

https://github.com/OWASP/www-chapter-newcastle-uk/blob/master/README.md

**Comment by jgadsden** [comment]
Totally! Good find - looks good to me

**Comment by craigfrancis** [comment]
Done :-)
