### ISSUE TITLE
Need to add sponsors 

### ISSUE THREAD

**Issue by katyanton** [OWASP/www-chapter-bristol-uk#8]
To add to the main page the meeting sponsors: 
1. ForgeRock
2. Just Eat
3. Ovo Energy 
4. RBS
5. Gresham Tech
6. Immersive Labs

something like the owasp London would be nice (https://owasp.org/www-chapter-london/)

**Comment by jgadsden** [comment]
Do we need permission to use the logos? ForgeRock is OK with this, and we use the Cray and Just Eat logos already on the meetup site, but was not sure if we needed to ask the other companies for permission

**Comment by katyanton** [comment]
I did not add Cray to the list-was bought by HP .
For the rest - yes it's fine to use them, you can get them from their website to ensure the latest version is used.

**Comment by jgadsden** [comment]
OK, @katyanton and @craigfrancis , I am working on it now and should have a PR later this evening

**Comment by jgadsden** [comment]
This has been done in PR #9 - can this issue be closed now?

**Comment by katyanton** [comment]
yeap - closed

**Comment by jgadsden** [comment]
There are still PRs #10 and #7 if you would like to merge those as well @katyanton ?
